services:
  mysql:
    image: mysql:8.4
    container_name: pescd-mysql
    restart: always
    environment:
      MYSQL_DATABASE: pescd_db
      MYSQL_USER: pescd_user
      MYSQL_PASSWORD: pescd_pass
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "pescd_user", "-ppescd_pass"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    ports:
      - "3307:3306"

volumes:
  mysql_data:
