spring.application.name=pescd
spring.datasource.url=jdbc:mysql://localhost:3306/pescd_db?useSSL=false&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true
#spring.datasource.username=pescd_user
#spring.datasource.password=pescd_pass
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=never
