package br.ufscar.dc.dsw.pescd.model;

public enum StatusInscricao {
    NAO_ENVIADO,
    PLANO_ENVIADO,
    PLANO_APROVADO,
    PLANO_REPROVADO,
    DOCUMENTACAO_ENVIADA,
    RELATORIO_ENVIADO,
    RELATORIO_APROVADO,
    RELATORIO_REPROVADO,
    CONCLUIDO_PELO_RESPONSAVEL,
    CONCLUIDO
}